Algoritmo "VerificaNumero"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
// Seção de Declarações das variáveis 
num1, num2: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite o primeiro número: ")
Leia(num1)
Escreval("Digite o segundo número:" )
Leia(num2)
Se(num1 > num2) Então
  Escreva("Número 1 é maior que o número 2!")
Senao
  Escreva("Número 2 é maior qur número 1!")
FimSe

Fimalgoritmo